### ISSUE TITLE
App freeze on android

### ISSUE THREAD

**Issue by Hrmojtahed** [gorhom/react-native-portal#24] opened 2022-04-07 12:44 UTC
portal package on ios works fine,but on android app freeze.
i use react-navigation and react-native-reanimated

**Comment by gurbela** [comment] 2022-05-03 17:50
any news?

**Comment by hodangnamtien** [comment] 2022-05-05 06:44
react-native-reanimated and use portal => problem

**Comment by thanhnvpk01168** [comment] 2022-05-16 09:12
@hodangnamtien I have to the same problem

**Comment by iamvucms** [comment] 2022-06-02 12:12
Same problem.

**Comment by miihauu** [comment] 2022-06-20 14:39
I am facing the same problem. Any news with fix to this? @gorhom

**Comment by bartlomiejwendt** [comment] 2022-06-20 14:41
The same issue on my end. Would be grateful for some updates about this issue from you. @gorhom

**Comment by AlanSl** [comment] 2022-06-20 14:55
Could the issue (and fix) be similar to this (solved) issue on `react-native-modalfy`? They're doing a similar thing to this library (using context for pure-JS portal/modal-like behaviour without using React Native's `Modal`) and their issue was also specific to Android when reanimated was in use - https://github.com/colorfy-software/react-native-modalfy/issues/66

(I don't know why there has been three comments on this issue in the last 20 minutes, mine is completely coincidental 😅)

**Comment by gorhom** [comment] 2022-06-20 15:20
Any reproducible sample code to work on ?

**Comment by miihauu** [comment] 2022-06-20 15:30
I am using `react-native-portal` with `react-native-bottom-sheet`.


Applying provider in App.tsx
`
const App = () => {
return (
PortalProvider>
                              <RootNavigator
                                initialState={initialNavigationState}
                                onStateChange={onNavigationStateChange}
                              />
                            </PortalProvider>
)}
`


Using Portal with BottomSheet. This `Sheet` component is showing with Map (Mapbox library) in background. 


`
const Sheet = () => {
  const { bottomSheetRef } = myContextHook()

  return (
    <Portal>
      <BottomSheet
        index={-1}
        ref={bottomSheetRef}
        snapPoints={[10, 75]}
        enablePanDownToClose
        backdropComponent={(props) => (
          <BottomSheetBackdrop {...props} pressBehavior={'close'} appearsOnIndex={0} disappearsOnIndex={-1} />
        )}
        onChange={() => {}}
      >
        <BottomSheetScrollView contentContainerStyle={{ paddingBottom: '8%' }}>
          <Box>
            My content
          </Box>
        </BottomSheetScrollView>
      </BottomSheet>
    </Portal>
  )
}
`


`  "dependencies": {
    "@gorhom/bottom-sheet": "^4.1.5",
    "@gorhom/portal": "^1.0.13",
    "react-native-reanimated": "^2.3.1",
    "react-native-screens": "3.10.2",
`

**Comment by AlanSl** [comment] 2022-06-21 09:59
I tried a few combinations of `reanimated` animations, portals and navigators on a standalone app on an Android device, and couldn't replicate this. Even navigating during an exit animation in a portal worked fine. 

So this is more subtle than "react-native-reanimated and use portal => problem". More example cases would help.

@miihauu There's a lot of possible causes in that example; dozens of animations within BottomSheet alone, plus the navigator. Does the issue still occur with that bottom-sheet / portal setup without the navigator? E.g. if you temporarily simplify it to this:

```jsx
const App = () => {
return (
  <PortalProvider>
    <View>/* Some pressable that brings up the bottom sheet */</View>
    <Sheet /> 
  </PortalProvider>
)}
```

**Comment by miihauu** [comment] 2022-06-23 10:52
@AlanSl Thank you for your involvment. I've figured out that app is not exactly freezing, but the bottom sheet is not reacting for dragging it down when it is wrapped in `<Portal></Portal>`. When I placed button inside sheet to closing it - it works, but I would like to have ability to use gestures. On iOS it works fine so only android devices have problems with that. 

Thanks and still looking for solution for that.

**Comment by miihauu** [comment] 2022-06-23 11:35
Ok, I have found a solution.

I wrapped my Portal provider with `GestureHandlerRootView`

```
<GestureHandlerRootView style={{ flex: 1 }}>
        <PortalProvider>
          <RootNavigator
                     initialState={initialNavigationState}
                     onStateChange={onNavigationStateChange}
              />
        </PortalProvider>
      </GestureHandlerRootView>
```

and my BottomSheet component looks like this:

```
<Portal>
<BottomSheet {...props] >
<Content />
</BottomSheet>
</Portal>
```

From my side is closed. Thanks for help.

**Comment by gorhom** [comment] 2022-06-23 20:51
thanks @miihauu & @AlanSl  for investigating this issue, i have added a section in the readme for the usage with gesture handler.

i'll close the ticket, if someone still faces the issue, please create a new issue

**Closed by gorhom** 2022-06-23 20:51 UTC

**Comment by lightrow** [comment] 2022-08-30 15:48
i just encountered this issue again. I think it might be due to "exiting" animation of an Animated.View. The structure i have is something like this
```
<PortalHost name="menu" />
<AppNavigator>
   ...many levels deeper a component that gets mounted/unmounted when menu is activated/dismissed
   <Portal hostName="menu">
      <Animated.View exiting={exitingAnimation} ...>
          ...
      </Animated.View>
   </Portal>
```
so maybe Animated.View tries to play its exiting animation but Portal does something upon unmount that breaks it all? But again it works fine on iOS...

**Comment by kunuit** [comment] 2023-02-12 18:29
@lightrow I commented this "exiting" code then fine but without animated. when re-comment and after first-time call exiting => I don't see any bottom sheets. How can we fix it?  And Seem I see a run function with 'worklet' maybe this bottomsheet also die

**Comment by truongnv98** [comment] 2024-08-12 07:51
I'm currently using the react-native-portal and BottomSheet component from @gorhom/bottom-sheet. I realize that if I use this code, the app will freeze:

`backdropComponent={props => (
  <BottomSheetBackdrop
    {...props}
    appearsOnIndex={1}
    disappearsOnIndex={-1}
  />
)}`

If I comment out the appearsOnIndex and disappearsOnIndex props, the app will work properly but there will be no backdrop.

And one more thing. I have this code in the MainActivity - onCreate function
`getWindow().setDecorFitsSystemWindows(false);` to apply the Android Edge to Edge 

@gorhom Can you please take a look

**Comment by dennis-Softfruit** [comment] 2025-09-18 11:33
> I'm currently using the react-native-portal and BottomSheet component from @gorhom/bottom-sheet. I realize that if I use this code, the app will freeze:
> 
> `backdropComponent={props => ( <BottomSheetBackdrop {...props} appearsOnIndex={1} disappearsOnIndex={-1} /> )}`
> 
> If I comment out the appearsOnIndex and disappearsOnIndex props, the app will work properly but there will be no backdrop.
> 
> And one more thing. I have this code in the MainActivity - onCreate function `getWindow().setDecorFitsSystemWindows(false);` to apply the Android Edge to Edge
> 
> [@gorhom](https://github.com/gorhom) Can you please take a look

Hi, any fixes for this issue ?

**Comment by ArseniiLyzenko** [comment] 2026-01-29 14:30
> I'm currently using the react-native-portal and BottomSheet component from @gorhom/bottom-sheet. I realize that if I use this code, the app will freeze:
> 
> `backdropComponent={props => ( <BottomSheetBackdrop {...props} appearsOnIndex={1} disappearsOnIndex={-1} /> )}`
> 
> If I comment out the appearsOnIndex and disappearsOnIndex props, the app will work properly but there will be no backdrop.

This is still relevant in 2026! It is occuring on some Android devices (Samsung Galaxy S24+) and emulators (Pixel 9, android 15.0, arm64, api 35 and Pixel 6 Pro - UpsideDownCake). Looking for a solution.

EDIT: Ended up using BottomSheetModal instead of BottomSheet to fix issue (btw it wasn't a freeze - a full-screen view was blocking all user touches)
